# This file was generated by liblab | https://liblab.com/
# pylint: disable=C0116, C0115

import unittest
from src.toolhouse.models.OpenAiAssistantsToolCall import OpenAiAssistantsToolCall


class TestOpenAiAssistantsToolCallModel(unittest.TestCase):
    def test_true(self):
        self.assertTrue(True)  # pylint: disable=W1503

    def test_open_ai_assistants_tool_call(self):
        # Create OpenAiAssistantsToolCall class instance
        test_model = OpenAiAssistantsToolCall(function={"vitae": 4}, id="iure")
        self.assertEqual(test_model.function, {"vitae": 4})
        self.assertEqual(test_model.id, "iure")

    def test_open_ai_assistants_tool_call_required_fields_missing(self):
        # Assert OpenAiAssistantsToolCall class generation fails without required fields
        with self.assertRaises(TypeError):
            # pylint: disable=E1120, W0612
            test_model = OpenAiAssistantsToolCall()  # noqa: F841


if __name__ == "__main__":
    unittest.main()
