# This file was generated by liblab | https://liblab.com/

import unittest
from src.toolhouse.models.AntropicTools import AntropicTools


class TestAntropicToolsModel(unittest.TestCase):
    def test_true(self):
        self.assertTrue(True)

    def test_antropic_tools(self):
        # Create AntropicTools class instance
        test_model = AntropicTools(
            description="optio", name="deleniti", input_schema={"impedit": 8}
        )
        self.assertEqual(test_model.description, "optio")
        self.assertEqual(test_model.name, "deleniti")
        self.assertEqual(test_model.input_schema, {"impedit": 8})

    def test_antropic_tools_required_fields_missing(self):
        # Assert AntropicTools class generation fails without required fields
        with self.assertRaises(TypeError):
            test_model = AntropicTools()


if __name__ == "__main__":
    unittest.main()
