# This file was generated by liblab | https://liblab.com/
# pylint: disable=C0116, C0115

import unittest
from src.toolhouse.models.GenericToolCall import GenericToolCall


class TestGenericToolRequestModel(unittest.TestCase):
    def test_true(self):
        self.assertTrue(True)  # pylint: disable=W1503

    def test_generic_tool_request(self):
        # Create GenericToolRequest class instance
        test_model = GenericToolCall(input={"deserunt": 8}, name="aliquid")
        self.assertEqual(test_model.input, {"deserunt": 8})
        self.assertEqual(test_model.name, "aliquid")

    def test_generic_tool_request_required_fields_missing(self):
        # Assert GenericToolRequest class generation fails without required fields
        with self.assertRaises(TypeError):
            # pylint: disable=E1120, W0612
            test_model = GenericToolCall()  # noqa: F841


if __name__ == "__main__":
    unittest.main()
