# This file was generated by liblab | https://liblab.com/
# pylint: disable=C0116

import unittest
from src.toolhouse.models.OpenAiToolCall import OpenAiToolCall


class TestOpenAiToolCallModel(unittest.TestCase):
    def test_true(self):
        self.assertTrue(True)  # pylint: disable=W1503

    def test_open_ai_tool_call(self):
        # Create OpenAiToolCall class instance
        test_model = OpenAiToolCall(
            type="function", function={"numquam": 9}, id="recusandae"
        )
        self.assertEqual(test_model.type, "function")
        self.assertEqual(test_model.function, {"numquam": 9})
        self.assertEqual(test_model.id, "recusandae")

    def test_open_ai_tool_call_required_fields_missing(self):
        # Assert OpenAiToolCall class generation fails without required fields
        with self.assertRaises(TypeError):
            # pylint: disable=E1120, W0612
            test_model = OpenAiToolCall()  # noqa: F841


if __name__ == "__main__":
    unittest.main()
