# This file was generated by liblab | https://liblab.com/
# pylint: disable=C0116, C0115

import unittest
from src.toolhouse.models.RunToolsRequest import RunToolsRequest


class TestRunToolsRequestModel(unittest.TestCase):
    def test_true(self):
        self.assertTrue(True)  # pylint: disable=W1503

    def test_run_tools_request(self):
        # Create RunToolsRequest class instance
        test_model = RunToolsRequest(
            content={"doloribus": 6}, provider="openai", metadata="foo", bundle="finance"
        )
        self.assertEqual(test_model.content, {"doloribus": 6})
        self.assertEqual(test_model.provider, "openai")
        self.assertEqual(test_model.metadata, "foo")
        self.assertEqual(test_model.bundle, "finance")

    def test_run_tools_request_required_fields_missing(self):
        # Assert RunToolsRequest class generation fails without required fields
        with self.assertRaises(TypeError):
            # pylint: disable=E1120, W0612
            test_model = RunToolsRequest()  # noqa: F841


if __name__ == "__main__":
    unittest.main()
