# This file was generated by liblab | https://liblab.com/
# pylint: disable=C0116, C0115

import unittest
from src.toolhouse.models.GetToolsRequest import GetToolsRequest


class TestGetToolsResponseModel(unittest.TestCase):
    def test_true(self):
        self.assertTrue(True)  # pylint: disable=W1503

    def test_get_tools_request(self):
        # Create RunToolsRequest class instance
        test_model = GetToolsRequest(
            provider="openai",
            metadata={"id": "pippo"}
        )
        self.assertEqual(test_model.provider, "openai")

    def test_get_tools_request_required_fields_missing(self):
        # Assert RunToolsRequest class generation fails without required fields
        with self.assertRaises(TypeError):
            # pylint: disable=E1120, W0612
            test_model = GetToolsRequest()  # noqa: F841


if __name__ == "__main__":
    unittest.main()
