# This file was generated by liblab | https://liblab.com/
# pylint: disable=C0116, C0115

import unittest
from src.toolhouse.models.OpenAiTools import OpenAiTools


class TestOpenAiToolsModel(unittest.TestCase):
    def test_true(self):
        self.assertTrue(True)  # pylint: disable=W1503

    def test_open_ai_tools(self):
        # Create OpenAiTools class instance
        test_model = OpenAiTools(type="function", function={"facere": 2})
        self.assertEqual(test_model.type, "function")
        self.assertEqual(test_model.function, {"facere": 2})

    def test_open_ai_tools_required_fields_missing(self):
        # Assert OpenAiTools class generation fails without required fields
        with self.assertRaises(TypeError):
            # pylint: disable=E1120, W0612
            test_model = OpenAiTools()  # noqa: F841


if __name__ == "__main__":
    unittest.main()
