# This file was generated by liblab | https://liblab.com/

from .base import BaseModel


class Input(dict):
    def __init__(self, *args, **kwargs):
        dict.__init__(self, *args, **kwargs)


class GenericToolCall(BaseModel):
    """
    Represents a tool call for Generic.
    """

    def __init__(self, input: Input, name: str, **kwargs):
        """
        Initialize GenericToolCall
        Parameters:
        ----------
            input_: Input_
            name: str
        """
        self.input = input
        self.name = name
